configserver:
    name: configuration-server
    status: config-server running !!!  https://github.com/kaztor-dirkoo/kaztor-dev

jhipster:
    security:
      authentication:
        jwt:
          base64-secret: ZTBlMTA3ZDAxMzYwN2UyYTQ3ZjI5ZTZhOGFlYWY0ODg1ZGNjMmYwMDFkNmY5NGYwYTBlM2VhNjk3ODRjZDQ5NjJlNTk2ZjkyMDNjZWI3NmJmN2UwMmFlYjQ1ZGViNDEyOTBiYQ==

# Enable /management/logfile endpoint for all apps
logging:
    file: ${java.io.tmpdir}/${spring.application.name}.log
eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
